# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pqQY6I_KjoGOcPJHrEVifadqHAFL3bA

### Experiment 3.1: Write a Python program to perform stemming using the Porter Stemmer. Apply stemming to the following words. Display the original words and their stems.
`playing, played, plays, studies, studying, connected, connection, computers`
"""

from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
words = ['playing', 'played', 'plays', 'studies', 'studying', 'connected', 'connection', 'computers']

print(f"{'Original Word':<15} -> {'Stem'}")
print("-" * 30)
for word in words:
    print(f"{word:<15} -> {stemmer.stem(word)}")

import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

"""### Experiment 3.2: Write a Python program to perform lemmatization on given input words:
`cats, dogs, running, runs, ran, studies, studying, better, children, mice, went, ate, leaves, caring`
"""

from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

lemmatizer = WordNetLemmatizer()
words = ['cats', 'dogs', 'running', 'runs', 'ran', 'studies', 'studying', 'better', 'children', 'mice', 'went', 'ate', 'leaves', 'caring']

pos_tags = {
    'cats': wordnet.NOUN, 'dogs': wordnet.NOUN, 'running': wordnet.VERB,
    'runs': wordnet.VERB, 'ran': wordnet.VERB, 'studies': wordnet.VERB,
    'studying': wordnet.VERB, 'better': wordnet.ADJ, 'children': wordnet.NOUN,
    'mice': wordnet.NOUN, 'went': wordnet.VERB, 'ate': wordnet.VERB,
    'leaves': wordnet.NOUN, 'caring': wordnet.VERB
}

print(f"{'Original Word':<15} -> {'Lemma'}")
print("-" * 30)
for word in words:
    lemma = lemmatizer.lemmatize(word, pos=pos_tags[word])
    print(f"{word:<15} -> {lemma}")

"""### Experiment 3.3: Write a Python program using Regular Expressions (Regex) to extract and process the following information from a text:
- Email addresses
- URLs
- Mobile numbers
- Hashtags
- Mentions

**Input Text:**
*Welcome to the Natural Language Processing workshop! For more information, visit https://www.nlpworkshop.com or www.python.org. You can contact the coordinator at nlpworkshop@gmail.com or support@python.org. For registration, call +91-9876543210 or 9123456789. Follow us on social media @NLPWorkshop and @PythonLearner. Share your experience using #NLP, #Python, and #MachineLearning. You can also visit https://github.com/NLPWorkshop for the latest updates.*
"""

import re

text = """Welcome to the Natural Language Processing workshop! For more information, visit https://www.nlpworkshop.com or www.python.org. You can contact the coordinator at nlpworkshop@gmail.com or support@python.org. For registration, call +91-9876543210 or 9123456789. Follow us on social media @NLPWorkshop and @PythonLearner. Share your experience using #NLP, #Python, and #MachineLearning. You can also visit https://github.com/NLPWorkshop for the latest updates."""

print("Email addresses :", re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b', text))
print("URLs            :", [u.rstrip('.,') for u in re.findall(r'https?://[^\s]+|\bwww\.[^\s]+\b', text)])
print("Mobile numbers  :", re.findall(r'(?:\+91[-\s]?)?[6-9]\d{9}', text))
print("Hashtags        :", re.findall(r'#[A-Za-z0-9_]+', text))
print("Mentions        :", re.findall(r'(?<!\S)@[A-Za-z0-9_]+', text))